const events = [
  {
    id: "evt_3K8poIDxyE66iaDh0a3NFumk",
    object: "event",
    api_version: "2020-08-27",
    created: 1640021897,
    data: {
      object: {
        id: "pi_3K8poIDxyE66iaDh0UK4D27U",
        object: "payment_intent",
        amount: 9900,
        amount_capturable: 0,
        amount_received: 9900,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: null,
        cancellation_reason: null,
        capture_method: "automatic",
        charges: {
          object: "list",
          data: [
            {
              id: "ch_3K8poIDxyE66iaDh09p9v0FB",
              object: "charge",
              amount: 9900,
              amount_captured: 9900,
              amount_refunded: 0,
              application: null,
              application_fee: null,
              application_fee_amount: null,
              balance_transaction: "txn_3K8poIDxyE66iaDh0ZmVm9jX",
              billing_details: {
                address: {
                  city: null,
                  country: "BD",
                  line1: null,
                  line2: null,
                  postal_code: null,
                  state: null,
                },
                email: "jafraaan@gmail.com",
                name: "Md Jafran Hasan",
                phone: null,
              },
              calculated_statement_descriptor: "WPPOOL.DEV",
              captured: true,
              created: 1640021897,
              currency: "usd",
              customer: "cus_KoSj75yRITQ5tI",
              description: null,
              destination: null,
              dispute: null,
              disputed: false,
              failure_code: null,
              failure_message: null,
              fraud_details: {},
              invoice: null,
              livemode: false,
              metadata: {},
              on_behalf_of: null,
              order: null,
              outcome: {
                network_status: "approved_by_network",
                reason: null,
                risk_level: "normal",
                risk_score: 14,
                seller_message: "Payment complete.",
                type: "authorized",
              },
              paid: true,
              payment_intent: "pi_3K8poIDxyE66iaDh0UK4D27U",
              payment_method: "pm_1K8poRDxyE66iaDhvAt54rTU",
              payment_method_details: {
                card: {
                  brand: "visa",
                  checks: {
                    address_line1_check: null,
                    address_postal_code_check: null,
                    cvc_check: "pass",
                  },
                  country: "US",
                  exp_month: 12,
                  exp_year: 2024,
                  fingerprint: "OO5cuJGMqqctynVi",
                  funding: "credit",
                  installments: null,
                  last4: "4242",
                  network: "visa",
                  three_d_secure: null,
                  wallet: null,
                },
                type: "card",
              },
              receipt_email: null,
              receipt_number: null,
              receipt_url:
                "https://pay.stripe.com/receipts/acct_1JvedlDxyE66iaDh/ch_3K8poIDxyE66iaDh09p9v0FB/rcpt_KoSjIiJA13IfQiBGdWqyx8ghHTXZpDf",
              refunded: false,
              refunds: {
                object: "list",
                data: [],
                has_more: false,
                total_count: 0,
                url: "/v1/charges/ch_3K8poIDxyE66iaDh09p9v0FB/refunds",
              },
              review: null,
              shipping: null,
              source: null,
              source_transfer: null,
              statement_descriptor: null,
              statement_descriptor_suffix: null,
              status: "succeeded",
              transfer_data: null,
              transfer_group: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: "/v1/charges?payment_intent=pi_3K8poIDxyE66iaDh0UK4D27U",
        },
        client_secret:
          "pi_3K8poIDxyE66iaDh0UK4D27U_secret_RnNXDo0XT6YcEO088QCFGK0oU",
        confirmation_method: "automatic",
        created: 1640021886,
        currency: "usd",
        customer: "cus_KoSj75yRITQ5tI",
        description: null,
        invoice: null,
        last_payment_error: null,
        livemode: false,
        metadata: {},
        next_action: null,
        on_behalf_of: null,
        payment_method: "pm_1K8poRDxyE66iaDhvAt54rTU",
        payment_method_options: {
          card: {
            installments: null,
            network: null,
            request_three_d_secure: "automatic",
          },
        },
        payment_method_types: ["card"],
        processing: null,
        receipt_email: null,
        review: null,
        setup_future_usage: null,
        shipping: null,
        source: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: "succeeded",
        transfer_data: null,
        transfer_group: null,
      },
    },
    livemode: false,
    pending_webhooks: 2,
    request: {
      id: "req_hzABDZC7zFN6wX",
      idempotency_key: "2913308b-aeed-4848-a371-6cad8c933b79",
    },
    type: "payment_intent.succeeded",
  },
  {
    id: "evt_3K8pq6DxyE66iaDh2Gp4FJvY",
    object: "event",
    api_version: "2020-08-27",
    created: 1640022000,
    data: {
      object: {
        id: "pi_3K8pq6DxyE66iaDh2e7hqXc3",
        object: "payment_intent",
        amount: 9900,
        amount_capturable: 0,
        amount_received: 9900,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: null,
        cancellation_reason: null,
        capture_method: "automatic",
        charges: {
          object: "list",
          data: [
            {
              id: "ch_3K8pq6DxyE66iaDh2wXicTZt",
              object: "charge",
              amount: 9900,
              amount_captured: 9900,
              amount_refunded: 0,
              application: null,
              application_fee: null,
              application_fee_amount: null,
              balance_transaction: "txn_3K8pq6DxyE66iaDh2KbDyUdq",
              billing_details: {
                address: {
                  city: null,
                  country: "BD",
                  line1: null,
                  line2: null,
                  postal_code: null,
                  state: null,
                },
                email: "jafraaan@gmail.com",
                name: "Md Jafran Hasan",
                phone: null,
              },
              calculated_statement_descriptor: "WPPOOL.DEV",
              captured: true,
              created: 1640021999,
              currency: "usd",
              customer: "cus_KoSlwCywMfhq51",
              description: "Subscription creation",
              destination: null,
              dispute: null,
              disputed: false,
              failure_code: null,
              failure_message: null,
              fraud_details: {},
              invoice: "in_1K8pq6DxyE66iaDhNYTC55Ch",
              livemode: false,
              metadata: {},
              on_behalf_of: null,
              order: null,
              outcome: {
                network_status: "approved_by_network",
                reason: null,
                risk_level: "normal",
                risk_score: 36,
                seller_message: "Payment complete.",
                type: "authorized",
              },
              paid: true,
              payment_intent: "pi_3K8pq6DxyE66iaDh2e7hqXc3",
              payment_method: "pm_1K8pq5DxyE66iaDhnlTcr5tX",
              payment_method_details: {
                card: {
                  brand: "visa",
                  checks: {
                    address_line1_check: null,
                    address_postal_code_check: null,
                    cvc_check: "pass",
                  },
                  country: "US",
                  exp_month: 12,
                  exp_year: 2024,
                  fingerprint: "OO5cuJGMqqctynVi",
                  funding: "credit",
                  installments: null,
                  last4: "4242",
                  network: "visa",
                  three_d_secure: null,
                  wallet: null,
                },
                type: "card",
              },
              receipt_email: null,
              receipt_number: null,
              receipt_url:
                "https://pay.stripe.com/receipts/acct_1JvedlDxyE66iaDh/ch_3K8pq6DxyE66iaDh2wXicTZt/rcpt_KoSltyM1OHyFwHP3ugdXK5FXaQ93esM",
              refunded: false,
              refunds: {
                object: "list",
                data: [],
                has_more: false,
                total_count: 0,
                url: "/v1/charges/ch_3K8pq6DxyE66iaDh2wXicTZt/refunds",
              },
              review: null,
              shipping: null,
              source: null,
              source_transfer: null,
              statement_descriptor: null,
              statement_descriptor_suffix: null,
              status: "succeeded",
              transfer_data: null,
              transfer_group: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: "/v1/charges?payment_intent=pi_3K8pq6DxyE66iaDh2e7hqXc3",
        },
        client_secret:
          "pi_3K8pq6DxyE66iaDh2e7hqXc3_secret_MalmgefTT17z8dTurXqzX51bm",
        confirmation_method: "automatic",
        created: 1640021998,
        currency: "usd",
        customer: "cus_KoSlwCywMfhq51",
        description: "Subscription creation",
        invoice: "in_1K8pq6DxyE66iaDhNYTC55Ch",
        last_payment_error: null,
        livemode: false,
        metadata: {},
        next_action: null,
        on_behalf_of: null,
        payment_method: "pm_1K8pq5DxyE66iaDhnlTcr5tX",
        payment_method_options: {
          card: {
            installments: null,
            network: null,
            request_three_d_secure: "automatic",
          },
        },
        payment_method_types: ["card"],
        processing: null,
        receipt_email: null,
        review: null,
        setup_future_usage: "off_session",
        shipping: null,
        source: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: "succeeded",
        transfer_data: null,
        transfer_group: null,
      },
    },
    livemode: false,
    pending_webhooks: 2,
    request: {
      id: "req_GVnpKG11rvM4uV",
      idempotency_key: "885eb537-4d8b-43e7-ae04-7154239dde0c",
    },
    type: "payment_intent.succeeded",
  },
  {
    id: "evt_1K8pq9DxyE66iaDhWluipb4N",
    object: "event",
    api_version: "2020-08-27",
    created: 1640022000,
    data: {
      object: {
        id: "cs_test_b1z9MyiuMViua2iGrn7JVXRM89dEhBEaBaMOkfHMhRPmiYCrgunPcSLSEk",
        object: "checkout.session",
        after_expiration: null,
        allow_promotion_codes: true,
        amount_subtotal: 9900,
        amount_total: 9900,
        automatic_tax: { enabled: false, status: null },
        billing_address_collection: "auto",
        cancel_url: "https://stripe.com",
        client_reference_id: null,
        consent: null,
        consent_collection: null,
        currency: "usd",
        customer: "cus_KoSlwCywMfhq51",
        customer_details: {
          email: "jafraaan@gmail.com",
          phone: null,
          tax_exempt: "none",
          tax_ids: [],
        },
        customer_email: null,
        expires_at: 1640108389,
        livemode: false,
        locale: "auto",
        metadata: {},
        mode: "subscription",
        payment_intent: null,
        payment_link: "plink_1K8eDjDxyE66iaDhEZ5QhxqH",
        payment_method_options: {},
        payment_method_types: ["card"],
        payment_status: "paid",
        phone_number_collection: { enabled: false },
        recovered_from: null,
        setup_intent: null,
        shipping: null,
        shipping_address_collection: null,
        shipping_options: [],
        shipping_rate: null,
        status: "complete",
        submit_type: null,
        subscription: "sub_1K8pq6DxyE66iaDhm4VF97ni",
        success_url: "https://stripe.com",
        total_details: {
          amount_discount: 0,
          amount_shipping: 0,
          amount_tax: 0,
        },
        url: null,
      },
    },
    livemode: false,
    pending_webhooks: 2,
    request: {
      id: "req_GVnpKG11rvM4uV",
      idempotency_key: "885eb537-4d8b-43e7-ae04-7154239dde0c",
    },
    type: "checkout.session.completed",
  },
];

var types = events.map((event) => event.type);

var filters = events

// filters = events.filter((event) =>
//   ["checkout.session.completed"].includes(event.type)
// );

filters = filters.map((filter) => filter.data.object);

var count = {};
types.forEach(typ => {
    (typ in count) ? count[typ]++ : count[typ] = 1
});

// console.log(types);
console.log(filters);
