name: WPCS PHP 7.4

on: [push]

env:
  PHP_VERSION: 7.4

jobs:
  wpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [$PHP_VERSION]
    name: PHP WPCS Check
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: |
        composer install
        
    - name: Run WPCS checks
      run: |
        ./vendor/bin/phpcs . --standard=WordPress
