name: Test WordPress Coding Standard

on:
  push:
    branches: [ master, develop ]

jobs:
  test-wpcs:
    runs-on: ubuntu-latest
    
    steps:
    - run: |
        echo 'PHP 8.1 is built-in on Ubuntu 22.04, skipping PHP installation.'
        
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Install PHP Code Sniffer
      run: |
        wget https://github.com/squizlabs/PHP_CodeSniffer/releases/download/3.7.1/phpcs.phar
        chmod +x phpcs.phar
        sudo mv phpcs.phar /usr/local/bin/phpcs
        
    - name: Install WordPress Coding Standards
      run: |
        wget https://github.com/WordPress/WordPress-Coding-Standards/archive/master.zip
        unzip master.zip
        mv WordPress-Coding-Standards-master ~/wpcs
        
    - name: Install PHPCompatiblity
      run: |
        wget https://github.com/PHPCompatibility/PHPCompatibility/archive/develop.zip
        unzip develop.zip
        mv PHPCompatibility-develop ~/PHPCompatibility
        phpcs --config-set installed_paths /home/$USER/wpcs,/home/$USER/PHPCompatibility
        echo 'PHPCS supported standards are..'
        phpcs -i
        
    - name: Loading PHPCS Configuration
      run: |
        wget -O phpcs.xml https://raw.githubusercontent.com/imjafran/wpcs/master/phpcs.xml
        mv phpcs.xml ~/phpcs.xml
    
    - name: Run PHPCS
      run: |
        phpcs --standard=~/phpcs.xml --extensions=php .
