name: Test WordPress Coding Standard

on:
    push:
        branches: [master, develop]

jobs:
    test-wpcs:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v3
            - id: foo
              uses: imjafran/wpcs@v1
              with:
                php: '7.4'
                text-domain: 'scf'
